language: node_js
node_js:
 - 4.2
 - 6
sudo: false
cache:
 directories:
  - node_modules
before_install:
 - npm install -g npm@3
 - npm --version
 - phantomjs --version
before_script:
 - chmod 777 ./travis_sauce_connect.sh
 - ./travis_sauce_connect.sh
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
after_script:
 - killall sc && sleep 5
env:
 global:
  - SAUCE_USERNAME=ariatemplates
  - SAUCE_ACCESS_KEY=620e638e-90d2-48e1-b66c-f9505dcb888b
addons:
 firefox: "36.0"
