language: node_js
node_js:
 - 0.10
 - 4.2
sudo: false
before_install:
 - npm install -g npm@3
 - npm --version
 - phantomjs --version
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
env:
 global:
  - SAUCE_USERNAME=ariatemplates
  - SAUCE_ACCESS_KEY=620e638e-90d2-48e1-b66c-f9505dcb888b
addons:
 sauce_connect: true
 firefox: "36.0"
